name: st-forecast
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pytorch>=2.1
  - pytorch-lightning>=2.1
  - numpy
  - pandas
  - scikit-learn
  - xarray
  - netcdf4
  - einops
  - hydra-core
  - matplotlib
  - seaborn
  - jupyterlab
